export const path = {
  HOME: "*",
  LOGIN: "login",
  INTRODUCE: "introduce",
  MALE: "nam",
  FEMALE: "nu",
  DETAILCT: ":category",
  CONTACT: "contact",
  BLOG: "blog",
  CHILDREN: "tre-em",
  DETAILPRODUCT: ":title/:pid",
  DETAILBLOG: ":bid",
  ADMIN: "admin",
  CREATE_PRODUCT: "create-product",
  DASHBOARD: "",
  MANAGER_ORDER: "manager-order",
  MANAGER_USER: "manager-user",
  MANAGER_BLOG: "manager-blog",
  CREATE_BLOG: "create-blog",

  MANAGER_PRODUCT: "manager-product",
  MENBER_LAYOUT: "menber",
  CART: "cart",
  EDIT_USER: "",
  USER: "user/",
};
